# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-22 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailedProducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
