# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-22 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TailedProducts', '0004_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TailedProducts.Product'),
        ),
    ]
