# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-22 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TailedProducts', '0006_usertoproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productprice',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='usertoproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='usertoproduct',
            old_name='user_id',
            new_name='user',
        ),
    ]
