# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailedProducts', '0007_auto_20180122_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
