# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TailedProducts', '0009_auto_20180329_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='min_price',
            new_name='best_price',
        ),
    ]
